export const site = {
  name: "Dharshan Paramasivan",
  short: "DP",
  role: "Full-Stack Engineer · QA Automation · API Security",
  tagline: "Building systems. Breaking assumptions. Securing what ships.",
  mantra: ["BUILD", "VERIFY", "SECURE", "SHIP"] as const,
  email: "dharshanparamasivan@gmail.com",
  phone: "+91 96776 54288",
  location: "Coimbatore",
  github: "https://github.com/DHARSHAN-PARAMASIVAN",
  linkedin: "https://www.linkedin.com/in/dharshan-paramasivan/",
  resume: "/Dharshan-Resume.pdf",
  education: {
    degree: "M.Sc. Software Systems",
    school: "PSG",
    score: "82%",
  },
};

export const projects = [
  {
    id: "vortex",
    number: "01",
    title: "VORTEXIOT",
    category: "Industrial IoT",
    year: "2026",
    blurb:
      "Machinery health monitoring with real-time telemetry, anomaly detection and cloud deployment.",
    stack: ["Next.js", "FastAPI", "PostgreSQL", "Kafka", "InfluxDB", "AWS", "Docker"],
    image: "/images/project-vortex.png",
    href: "https://machinary-one.vercel.app/",
    featured: true,
  },
  {
    id: "appointments",
    number: "02",
    title: "APPOINTMENTS",
    category: "Django · PostgreSQL",
    year: "2025",
    blurb: "Role-based booking system with secure access control and optimized scheduling.",
    stack: ["Django", "Python", "PostgreSQL"],
    image: "/images/project-appointments.png",
    href: null,
    featured: false,
  },
  {
    id: "security",
    number: "03",
    title: "API SECURITY LAB",
    category: "VAPT · API Security",
    year: "2024",
    blurb: "Endpoint discovery, auth testing, and hardening recommendations for APIs.",
    stack: ["Burp Suite", "OWASP ZAP", "Postman"],
    image: "/images/project-security.png",
    href: null,
    featured: false,
  },
  {
    id: "automation",
    number: "04",
    title: "AUTOMATION SUITE",
    category: "Selenium · Cucumber",
    year: "2025",
    blurb: "End-to-end BDD automation covering login and critical data-entry flows.",
    stack: ["Selenium", "Cucumber", "Java"],
    image: "/images/project-automation.png",
    href: null,
    featured: false,
  },
];

export const journey = [
  {
    year: "2025",
    org: "Fulcrum Technologies",
    role: "Software Tester Intern",
    focus: "Selenium · Cucumber · Automation",
    highlight: "40% testing-time reduction",
  },
  {
    year: "2025",
    org: "Pinsphere Solutions",
    role: "Full-Stack Developer Intern",
    focus: "Django · PostgreSQL · REST APIs",
    highlight: "25% backend performance improvement",
  },
  {
    year: "2026",
    org: "VortexIoT",
    role: "Industrial IoT Platform",
    focus: "Next.js · FastAPI · Kafka · AWS",
    highlight: "Live production deployment",
  },
];

export const skills = [
  "JAVA",
  "PYTHON",
  "JAVASCRIPT",
  "REACT",
  "NEXT.JS",
  "DJANGO",
  "FASTAPI",
  "POSTGRESQL",
  "MONGODB",
  "KAFKA",
  "AWS",
  "DOCKER",
  "SELENIUM",
  "CUCUMBER",
  "BURP SUITE",
  "OWASP ZAP",
  "JMETER",
  "GIT",
];

export const interests = [
  "Full-stack engineering",
  "Cloud",
  "Cybersecurity",
  "QA automation",
  "Data",
  "IoT",
  "AI",
];
